### ISSUE TITLE
Edit: Correct link for current encryption implementation in 4.2.1

### ISSUE THREAD

**Issue by m-005** [xmtp/litepaper#12]
At the bottom of 4.2.1, there's a link (https://xmtp.org/docs/client-sdk/security) to the current documentation for encrypting communications that routes to a Page Not Found. I believe the correct link is now: https://xmtp.org/docs/dev-concepts/invitation-and-message-encryption

**Comment by jhaaaa** [comment]
Thank you very much, @m-005! <3 <3 <3

I've created page redirects for https://xmtp.org/docs/client-sdk/security and https://xmtp.org/docs/client-sdk/security/ pointing to the correct location you've called out: https://xmtp.org/docs/dev-concepts/invitation-and-message-encryption
